services:

  simulador:
    build:
      context: .
      dockerfile: docker/Dockerfile.simulador
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=8883
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=Fabrica123
      - TOPIC=fabrica/raw
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  processador:
    build:
      context: .
      dockerfile: docker/Dockerfile.processador
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=8883
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=Fabrica123
      - INPUT_TOPIC=fabrica/raw
      - OUTPUT_TOPIC=fabrica/processado
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  banco_dados:
    build:
      context: .
      dockerfile: docker/Dockerfile.banco_dados
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=8883
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=Fabrica123
      - INPUT_TOPIC=fabrica/raw
      - OUTPUT_TOPIC=fabrica/processado
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"