FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/banco_dados.py .
COPY src/common ./common

CMD ["python", "-u", "banco_dados.py"]